CREATE TABLE "RESOURCE_TABLE_APPLICATION"
(
    "RESOURCE_TABLE_ENTID" NUMBER(19,0) NOT NULL ENABLE,
    "APPLICATIONS_ENTID"   NUMBER(19,0) NOT NULL ENABLE,
    PRIMARY KEY ("RESOURCE_TABLE_ENTID", "APPLICATIONS_ENTID"),
    CONSTRAINT "fk_app_entid" FOREIGN KEY ("APPLICATIONS_ENTID") REFERENCES "APPLICATION" ("ENTID") ENABLE,
    CONSTRAINT "fk_resource_entid" FOREIGN KEY ("RESOURCE_TABLE_ENTID") REFERENCES "RESOURCE_TABLE" ("ENTID") ENABLE
);

CREATE TABLE "LOGIN_APPLICATION"
(
    "LOGIN_ENTID"        NUMBER(19,0) NOT NULL ENABLE,
    "APPLICATIONS_ENTID" NUMBER(19,0) NOT NULL ENABLE,
    PRIMARY KEY ("LOGIN_ENTID", "APPLICATIONS_ENTID"),
    CONSTRAINT "fk_login_entid" FOREIGN KEY ("LOGIN_ENTID") REFERENCES "LOGIN" ("ENTID") ENABLE,
    CONSTRAINT "fk_application_entid" FOREIGN KEY ("APPLICATIONS_ENTID") REFERENCES "APPLICATION" ("ENTID") ENABLE
);
  
ALTER TABLE "APPLICATION" ADD  
(	
	"CREATED" TIMESTAMP (6),
    "CREATEDBY"  VARCHAR2(255 CHAR),
    "DATAORIGIN" VARCHAR2(255 CHAR),
    "UPDATED" TIMESTAMP (6),
    "UPDATEDBY" VARCHAR2(255 CHAR)
);

ALTER TABLE "APPLICATIONINSTANCE" ADD  
(	
	"CREATED" TIMESTAMP (6),
    "CREATEDBY"  VARCHAR2(255 CHAR),
    "DATAORIGIN" VARCHAR2(255 CHAR),
    "UPDATED" TIMESTAMP (6),
    "UPDATEDBY" VARCHAR2(255 CHAR)
);

ALTER TABLE "CLUSTERS" ADD  
(	
	"CREATED" TIMESTAMP (6),
    "CREATEDBY"  VARCHAR2(255 CHAR),
    "DATAORIGIN" VARCHAR2(255 CHAR),
    "UPDATED" TIMESTAMP (6),
    "UPDATEDBY" VARCHAR2(255 CHAR)
);

ALTER TABLE "ENVIRONMENTPART" ADD  
(	
	"CREATED" TIMESTAMP (6),
    "CREATEDBY"  VARCHAR2(255 CHAR),
    "DATAORIGIN" VARCHAR2(255 CHAR),
    "UPDATED" TIMESTAMP (6),
    "UPDATEDBY" VARCHAR2(255 CHAR)
);

ALTER TABLE "NODE" ADD  
(	
	"CREATED" TIMESTAMP (6),
    "CREATEDBY"  VARCHAR2(255 CHAR),
    "DATAORIGIN" VARCHAR2(255 CHAR),
    "UPDATED" TIMESTAMP (6),
    "UPDATEDBY" VARCHAR2(255 CHAR)
);

ALTER TABLE "LOGIN" ADD  
(	
	"CREATED" TIMESTAMP (6),
    "CREATEDBY"  VARCHAR2(255 CHAR),
    "DATAORIGIN" VARCHAR2(255 CHAR),
    "UPDATED" TIMESTAMP (6),
    "UPDATEDBY" VARCHAR2(255 CHAR)
);

ALTER TABLE "FILEENTITY" ADD  
(	
	"CREATED" TIMESTAMP (6),
    "CREATEDBY"  VARCHAR2(255 CHAR),
    "DATAORIGIN" VARCHAR2(255 CHAR),
    "UPDATED" TIMESTAMP (6),
    "UPDATEDBY" VARCHAR2(255 CHAR)
);

ALTER TABLE "PORTFOLIO" ADD  
(	
	"CREATED" TIMESTAMP (6),
    "CREATEDBY"  VARCHAR2(255 CHAR),
    "DATAORIGIN" VARCHAR2(255 CHAR),
    "UPDATED" TIMESTAMP (6),
    "UPDATEDBY" VARCHAR2(255 CHAR)
);

ALTER TABLE "RESOURCE_TABLE" ADD  
(	
	"CREATED" TIMESTAMP (6),
    "CREATEDBY"  VARCHAR2(255 CHAR),
    "DATAORIGIN" VARCHAR2(255 CHAR),
    "UPDATED" TIMESTAMP (6),
    "UPDATEDBY" VARCHAR2(255 CHAR)
);