apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "fasit"
  namespace: "team-atom"
  labels:
    team: "team-atom"
spec:
  resources:
    limits:
       cpu: 500m # app will have its cpu usage throttled if exceeding this limit
       memory: 2Gi  # app will be killed if exceeding these limits
    requests: # App is guaranteed the requested resources and  will be scheduled on nodes with at least this amount of resources available
       cpu: 200m
       memory: 512Mi
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: "/conf/isalive"
    initialDelay: 90
    timeout: 2
  readiness:
    path: "/conf/isalive"
    initialDelay: 90
    timeout: 2
  ingresses: # Optional. List of ingress URLs that will route HTTP traffic to the application.
    {{#each ingresses}}
    - "{{this}}"
    {{/each}}
  kafka:
    pool: {{ KAFKA_POOL }}
  env:
    - name: "LOG_OUTPUT"
      value: "JSON"
    - name: "ENVIRONMENT_NAME"
      value: {{ ENVIRONMENT_NAME }}
    - name: "ENVIRONMENT_CLASS"
      value: {{ ENVIRONMENT_CLASS }}
    - name: "ENVCONFDB_URL"
      value: {{ ENVCONFDB_URL }}
    - name: "LDAP_USER_BASEDN"
      value: {{ LDAP_USER_BASEDN }}
    - name: "LDAP_SERVICEUSER_BASEDN"
      value: {{ LDAP_SERVICEUSER_BASEDN }}
    - name: "LDAP_DOMAIN"
      value: {{ LDAP_DOMAIN }}
    - name: "LDAP_BASEDN"
      value: {{ LDAP_BASEDN }}
    - name: "LDAP_URL"
      value: {{ LDAP_URL }}
    - name: "VAULT_URL"
      value: {{ VAULT_URL }}
    - name: "DEPLOYLOG_V1_URL"
      value: {{ DEPLOYLOG_V1_URL }}
    - name: "ROLE_OPERATIONS_GROUPS"
      value: {{ ROLE_OPERATIONS_GROUPS }}
    - name: "ROLE_PROD_OPERATIONS_GROUPS"
      value: {{ ROLE_PROD_OPERATIONS_GROUPS }}
    - name: "ROLE_SUPERUSER_GROUPS"
      value: {{ ROLE_SUPERUSER_GROUPS }}
    - name: "KAFKA_DEPLOYMENT_EVENT_TOPIC"
      value: {{ KAFKA_DEPLOYMENT_EVENT_TOPIC }}
    - name: "OTEL_RESOURCE_ATTRIBUTES"
      value: "deployment.environment.name={{ENVIRONMENT_CLASS}}"

  vault:
    enabled: true
    paths:
      - kvPath: {{ db-vault-path }}
        mountPath: "/secrets/oracle/envconfDB"
      - kvPath: {{ ldap-user-vault-path }}
        mountPath: "/secrets/ldap/ldap"
      - kvPath: {{ fasit-user-vault-path }}
        mountPath: "/secrets/credential/srvfasit"
      - kvPath: {{ keystore-vault-path }}
        mountPath: "/secrets/certificate/fasit-keystore"
      - kvPath: {{ kafka-user-vault-path }}
        mountPath: "/secrets/credential/fasit.kafka.user"

  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
      destinations:
        - id: "grafana-lgtm"
        - id: "elastic-apm"
