name: Build and deploy fasit

on:
  push

env:
  TEAM: team-atom
permissions:
  contents: read
  id-token: write

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cache Maven dependencies
        uses: actions/cache@preview
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: '8.0.x'
      - name: Test
        run: mvn test  -B -e -X

  build:
    name: Build and public docker image
    needs: test
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - uses: actions/checkout@v1
      - name: Build artifact
        run: mvn package -DskipTests=true -B

      - uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: ${{ env.TEAM }}
          tag: ${{ github.sha }}
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

  deploy-dev:
     name: Deploy to dev-fss
     needs: build
     if: github.ref == 'refs/heads/master'
     runs-on: ubuntu-latest
     steps:
        - uses: actions/checkout@v2
        - uses: nais/deploy/actions/deploy@v2
          env:
            CLUSTER: dev-fss
            RESOURCE: nais/naiserator.yml
            VAR: image=${{ needs.build.outputs.image }}
            VARS: nais/dev-config.json

  deploy-prod:
    name: Deploy to prod-fss
    needs:
      - build
      - deploy-dev
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-fss
          RESOURCE: nais/naiserator.yml
          VAR: image=${{ needs.build.outputs.image }}
          VARS: nais/prod-config.json